### ISSUE TITLE
Multiple pages support

### ISSUE THREAD

**Issue by harryfei** [sheebz/phantom-proxy#26]
Do you have a plan to support open multiple pages?
Sometimes, we need it.

**Comment by AndrewRayCode** [comment]
are there other libraries that support this? and does phantomjs actually support this?

**Comment by sheebz** [comment]
Short answer is not at this point.  I think it would add unnecessary complexity to the interface at this point.  You might want to look into the version 1.8 webdriver implementation for this if you really need it.  

DelvarWorld - I believe that phantom does support it as page.create() returns a local variable.  I'm not sure I see the benefit of having multiple pages though - maybe to simulate tabs?  This would really be a drastic change though - the page object is basically a singleton on the server process in phantom proxy.

**Comment by simontabor** [comment]
Having multiple pages is kind of useful if you don't want the ridiculous overhead of booting phantom for every page request. Makes this module, unfortunately, useless for many services looking to run phantomjs properly in production. Say, for example, you're handling 5 req/s and that means booting 5 phantomjs'/sec which is crazy.

I urge you to look into this again! phantomjs-node is truly awful.

**Comment by AndrewRayCode** [comment]
@simontabor I agree that having a non 1:1 phantom interface is annoying. Can you give a possible use case for multiple pages? Making this change will probably require a very large refactor, do knowing what would make for good tests will be helpful. And yeah, the other node driver options for phantom are awful :)

**Comment by simontabor** [comment]
@DelvarWorld I took a look and it probably would be a fairly large refactor, happy to help out if needed.

Yeah sure, it's mainly for when using phantomjs to actually serve as an API to users, for example as a thumbnailing service where you might be wanting to render 10+ images at the same time (or any number, for that fact). AFAIK, phantomjs itself will only be single threaded so for higher numbers people should be booting up a phantomjs for each core and load balance over that.

The use case which is what I'd actually be using this for is a service at GoSquared where we load the website and check if the GoSquared tracking code is installed. Demo at http://checkbot.gosquared.com/GSN-757634-O. In that case, it loads simontabor.com and checks for the right tracking code. Basically, it's got to handle quite a lot of requests and booting a phantomjs for each one would be just a tad crazy.

Hope that helps :)

**Comment by john-clarke** [comment]
I have another use-case for a multi-page PhantomJS server. I'd like to use a node.js + phantom-proxy stack to rasterize D3.js visualizations as PNG. A simple example is a pie chart template for which I can inject the chart parameters and render a new pie chart PNG. The inject + page.render() process takes about 50-100ms plus ~2 seconds to open the visualization/page initially. In a production environment I envision at least 10 and up to hundreds of visualizations that I'd like to keep open and only inject the parameters to avoid re-opening the same page/visualization on each render.

Currently, the only option I have is to cache a proxy object for every visualization but the performance would be bad and I'd use about 32Mb of memory for each instance. In comparison, maintaining an array of page objects in PhantomJS works well and only uses about 500kb extra per page. I think the challenge will be to enable the proxy and phantomjs server to distinguish between pages in the array and potentially special garbage collection given the number of pages.

**Comment by AndrewRayCode** [comment]
@sheebz can you please reopen this and mark it as an improvement?
