### ISSUE TITLE
Consider transferring ownership of this project to me

### ISSUE THREAD

**Issue by AndrewRayCode** [sheebz/phantom-proxy#30]
Has the time come? I am currently heavily invested in the proxy, and have made many critical changes, and right now am more active in the project.

I'm not sure what your current involvement is, but I would like to see faster bug fixes if possible, of which transferring ownership would help.

**Comment by estliberitas** [comment]
:+1: for transfer

**Comment by estliberitas** [comment]
Also I'm interested in total reformatting of code (seems no coding convention is used now) and refactoring of code. Can help w/ this thus now my projects are very connected with phantom and this node.js module.

**Comment by AndrewRayCode** [comment]
agreed. I'm also pretty sure everything in `lib/request` should be a submodule, or even just a dependency, but I need to look through the logs to make sure he hasn't modified it

**Comment by throughnothing** [comment]
:+1:

**Comment by kevzettler** [comment]
:+1:

**Comment by ironcamel** [comment]
:+1:

**Comment by AndrewRayCode** [comment]
:8ball:

**Comment by pwlmc** [comment]
:+1:

**Comment by sheebz** [comment]
@DelvarWorld I understand you guys are heavily invested in this, and I appreciate the investment you guys have made.  I have made a pretty significant investment as well.  I have not had the luxury of owning a successful project before.  I'm not going to transfer ownership, but I will look into giving administrative control to a reliable contributor.

**Comment by estliberitas** [comment]
@sheebz okz, bro, understand ya too :)

**Comment by sheebz** [comment]
@estliberitas Not opposed to it, but need more info there.  Please explain what convention you think should be used and how it would benefit this project.

**Comment by sheebz** [comment]
@DelvarWorld the reason request is in lib is because I had to modify it to get it to work with phantomjs.   Unfortunately, the phantomjs server module expects a sentence case Content-Length header.  The request lib sends a lower case version of the header.  It was an expedient solution, if there is a cleaner way to do it I'm all for it.

**Comment by estliberitas** [comment]
@sheebz for example:
- do not wrap Node.js scripts into self-invoking functions, thus code is always gets wrapped by node;
- clean out of comments - as for me, really annoying, readability suffers;
- maybe use 2 indent for compact code;
- all the vars which will be used in any case for given func, should be defined at the beginning of the func in order of their first assignation - +5 to readability :)

The main aim - have no errors from js(hint|lint). I find first one more fitting.

**Comment by sheebz** [comment]
@estliberitas 
- Ok, I guess that makes sense, I was under the impression that using IIFEs was a best practice, maybe not for node modules?  
- By clean out comments, do you mean get rid of all comments?  There's not a ton of comments to begin with, but there are some spots that at least require an explanation.  I'll can an issue to remove unneeded comments.
- I'm not a fan of 2 space tabs, but I'm not opposed to changing either.  I'll have to see what the standard seems to be here, other opinions would be good.
- Yes, I agree with this. 

I'm going to create an issue to add grunt for building,linting running tests.  That should include a jshint configuration.  That should help address some of these concerns.

**Comment by AndrewRayCode** [comment]
fyi, 2 spaces are the devil and only used by people with bowel problems. +1 for 4 spaces

**Comment by estliberitas** [comment]
@DelvarWorld go, say this to express, Node, connect devs, ok?

**Comment by AndrewRayCode** [comment]
they already have bowel problems, so they won't listen. we can escape that madness, though.

**Comment by estliberitas** [comment]
> they already have bowel problems, so they won't listen. we can escape that
> madness, though

Your argument "I do not like smth." is not an argument, dude. At least I
have no problems viewing code with 2-space indentation, if code is written
well. From the other side I see that in some cases we have 16-24 chars
indentation - pyramids of doom were the reason of promises development. So
if we have callback'd code it's better to keep it compact.

Maybe, Andrew, you will oppose in such way rather than wasting words and
acting like...?
