### ISSUE TITLE
Unused (?) option eventStreamPath, or is it.

### ISSUE THREAD

**Issue by dmdeklerk** [sheebz/phantom-proxy#37]
Please explain what the option "eventStreamPath" does? 
Please see its usage here: https://github.com/sheebz/phantom-proxy/blob/master/lib/proxy.js#L271
Seems like it is not used in phantom-proxy as it is not even passed to phantomjs.

**Comment by sheebz** [comment]
@dmdeklerk, its legacy code, not used anymore and should be removed.  In the beginning I had some struggles with finding an efficient way to get notifications from server - a deprecated solution was to have server write events to file, then have client listen for file changes and parse events from filestream.  We are now using socket.io which has worked out pretty well so far. I will clean up references, thanks for pointing this out.
