### ISSUE TITLE
Add support for aborting requests

### ISSUE THREAD

**Issue by simontabor** [sheebz/phantom-proxy#41]
https://code.google.com/p/phantomjs/issues/detail?id=230

Is this possible? Would be really handy

**Comment by sheebz** [comment]
Looks like its slated for version 1.9, which is probably a good 6 months or so out at least.  But I believe we will be able to make this work.

**Comment by simontabor** [comment]
Ah damn, good spot - thought it was in 1.8. Good news it should possible, shame I'll have to wait :(

Thanks
