### ISSUE TITLE
proxy.page.set dosen't work

### ISSUE THREAD

**Issue by skotchio** [sheebz/phantom-proxy#50]
Here is the example:

```
var phantomProxy = require('phantom-proxy');

phantomProxy.create({}, function (proxy) {
   proxy.page.set('paperSize', {format: 'A4', orientation: 'landscape'}, function (result) {
     proxy.page.render('./test.png', function (result) {
         proxy.end(function () {console.log('done');});
     });
   });
});
```

At the end of story I get test.png file with the default 400x300 dimensions.

**Comment by reverie** [comment]
Contrary to the docs, I had to use page.set('settings, {..}) just to set the userAgent. Maybe the same thing will work for you.

**Comment by reverie** [comment]
Yes, try page.settings.set('paperSize', ...).

I'd also try removing any calls to page.get, as that was triggering a crash later on for me. (No idea why.)
