### ISSUE TITLE
path of phantomjs should be available as an option for non standard installs

### ISSUE THREAD

**Issue by CrisFavero** [sheebz/phantom-proxy#54]
In finding issue #53 i would also suggest that the location of phantomjs be available as an option for input as in many hosting cases the binaries may not necessarily be available in the  path and have an alternative location.  

This should operate such that if the option is not set the fall back is to use the current phantomjs hardcoded in.

**Comment by mark-hahn** [comment]
+1

**Comment by mpetrovich** [comment]
+1

The lack of a binary path option makes this library non-portable.
