### ISSUE TITLE
Few phantom proxy instances

### ISSUE THREAD

**Issue by WoZ** [sheebz/phantom-proxy#56]
I noticed that I can't create few instances of phantom proxy. Connection with previously created instances brokes every time I call phantomProxy.create because it rewrites context. How can I solve this problem? Thanks.

**Comment by WoZ** [comment]
Simple hack. You should fake context and save it to call end method.

``` javascript
var phantomProxy = require('phantom-proxy');
var context = {};

phantomProxy.create.call(context, options, callback);
phantomProxy.end.call(context, callback);
```

**Comment by estliberitas** [comment]
Hah, cool, will check :)
