### ISSUE TITLE
'undefined' is not a function (evaluating 'require('./webpage').create(this)')

### ISSUE THREAD

**Issue by OllieJennings** [sheebz/phantom-proxy#7]
So l created a fresh node project with phatom-proxy, followed one of the examples in your readme.md file, and this is the error l was met with.

'undefined' is not a function (evaluating 'require('./webpage').create(this)')
/node_modules/phantom-proxy/lib/server/webserver.js:11
/node_modules/phantom-proxy/lib/server/webserver.js:164
/node_modules/phantom-proxy/lib/server/webserver.js:165

I am currently running ubuntu 12.04, with node version v.0.9.2-pre and phatomjs version 1.7.0

I help would be appreciated.

**Comment by sheebz** [comment]
looking into it

**Comment by sheebz** [comment]
this specific bug is fixed on ubuntu, however several unit tests are not passing for ubuntu, so I'm hesitant to say that its working perfectly there.

**Comment by roman4e** [comment]
Still have this error on version 0.3.0
```
var page = wp.create();
              ^
TypeError: wp.create is not a function
```
